pub_c_hdrs = {h}{**}

./: $pub_c_hdrs

# Install into the cpptrace/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{h}{*}:
{
  install         = include/ctrace/
  install.subdirs = true
}
