intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.

# Public headers.
#
pub_c   = [dir_path] ../include/ctrace/
pub_cpp = [dir_path] ../include/cpptrace/

include $pub_c
include $pub_cpp

pub_c_hdrs   = $($pub_c/ pub_c_hdrs)
pub_cpp_hdrs = $($pub_cpp/ pub_cpp_hdrs)

lib{cpptrace}: $pub_c/{$pub_c_hdrs}
lib{cpptrace}: $pub_cpp/{$pub_cpp_hdrs}

# Private headers, sources, and dependencies.
#
lib{cpptrace}: {hxx cxx}{**}

# Build options.
#
out_pfx_inc = [dir_path] $out_root/include/
src_pfx_inc = [dir_path] $src_root/include/
out_pfx_src = [dir_path] $out_root/src/
src_pfx_src = [dir_path] $src_root/src/

cxx.poptions =+ "-I$out_pfx_src" "-I$src_pfx_src" \
                "-I$out_pfx_inc" "-I$src_pfx_inc"

# Export symbol visibility control.
#
cxx.poptions += "-Dcpptrace_lib_EXPORTS"

# Optional library dependencies.
#
if $config.libcpptrace.get_symbols_with_libbacktrace
{
  lib{cpptrace}: cxx.libs        += -lbacktrace -ldl
  lib{cpptrace}: cxx.export.libs += -lbacktrace -ldl
}

if $config.libcpptrace.get_symbols_with_libdl
{
  lib{cpptrace}: cxx.libs        += -ldl
  lib{cpptrace}: cxx.export.libs += -ldl
}

if ($config.libcpptrace.get_symbols_with_addr2line && ($cxx.target.class == 'linux' || $cxx.target.class == 'bsd'))
{
  lib{cpptrace}: cxx.libs        += -ldl
  lib{cpptrace}: cxx.export.libs += -ldl
}

if $config.libcpptrace.get_symbols_with_libdwarf
{
  import intf_libs += libdwarf%lib{dwarf}

  lib{cpptrace}: cxx.libs        += -ldwarf -lz -lzstd
  lib{cpptrace}: cxx.export.libs += -ldwarf -lz -lzstd

  if ($cxx.target.class == 'linux' || $cxx.target.class == 'bsd')
  {
    lib{cpptrace}: cxx.libs        += -ldl
    lib{cpptrace}: cxx.export.libs += -ldl
  }
}

if ($config.libcpptrace.unwind_with_libunwind && $cxx.target.class != 'macos')
{
  lib{cpptrace}: cxx.libs        += -lunwind
  lib{cpptrace}: cxx.export.libs += -lunwind
}

need_dbghelp = ($config.libcpptrace.get_symbols_with_dbghelp || \
                $config.libcpptrace.unwind_with_dbghelp      || \
                $config.libcpptrace.demangle_with_winapi)

if $need_dbghelp
{
  if ($cxx.target.class == 'windows')
  {
    if ($cxx.target.system == 'mingw32')
    {
      lib{cpptrace}: cxx.libs        += -ldbghelp
      lib{cpptrace}: cxx.export.libs += -ldbghelp
    }
    else
    {
      lib{cpptrace}: cxx.libs        += DbgHelp.lib
      lib{cpptrace}: cxx.export.libs += DbgHelp.lib
    }
  }
}

# Preprocessor feature flags.
#
if $config.libcpptrace.get_symbols_with_libbacktrace
  lib{cpptrace}: cxx.poptions += -DCPPTRACE_GET_SYMBOLS_WITH_LIBBACKTRACE

if $config.libcpptrace.get_symbols_with_libdwarf
  lib{cpptrace}: cxx.poptions += -DCPPTRACE_GET_SYMBOLS_WITH_LIBDWARF

if $config.libcpptrace.get_symbols_with_libdl
  lib{cpptrace}: cxx.poptions += -DCPPTRACE_GET_SYMBOLS_WITH_LIBDL

if $config.libcpptrace.get_symbols_with_addr2line
  lib{cpptrace}: cxx.poptions += -DCPPTRACE_GET_SYMBOLS_WITH_ADDR2LINE

if $config.libcpptrace.get_symbols_with_dbghelp
  lib{cpptrace}: cxx.poptions += -DCPPTRACE_GET_SYMBOLS_WITH_DBGHELP

if $config.libcpptrace.get_symbols_with_nothing
  lib{cpptrace}: cxx.poptions += -DCPPTRACE_GET_SYMBOLS_WITH_NOTHING

if $config.libcpptrace.unwind_with_unwind
  lib{cpptrace}: cxx.poptions += -DCPPTRACE_UNWIND_WITH_UNWIND

if $config.libcpptrace.unwind_with_libunwind
  lib{cpptrace}: cxx.poptions += -DCPPTRACE_UNWIND_WITH_LIBUNWIND

if $config.libcpptrace.unwind_with_execinfo
  lib{cpptrace}: cxx.poptions += -DCPPTRACE_UNWIND_WITH_EXECINFO

if $config.libcpptrace.unwind_with_winapi
  lib{cpptrace}: cxx.poptions += -DCPPTRACE_UNWIND_WITH_WINAPI

if $config.libcpptrace.unwind_with_dbghelp
  lib{cpptrace}: cxx.poptions += -DCPPTRACE_UNWIND_WITH_DBGHELP

if $config.libcpptrace.unwind_with_nothing
  lib{cpptrace}: cxx.poptions += -DCPPTRACE_UNWIND_WITH_NOTHING

if $config.libcpptrace.demangle_with_cxxabi
  lib{cpptrace}: cxx.poptions += -DCPPTRACE_DEMANGLE_WITH_CXXABI

if $config.libcpptrace.demangle_with_winapi
  lib{cpptrace}: cxx.poptions += -DCPPTRACE_DEMANGLE_WITH_WINAPI

if $config.libcpptrace.demangle_with_nothing
  lib{cpptrace}: cxx.poptions += -DCPPTRACE_DEMANGLE_WITH_NOTHING

if ($config.libcpptrace.backtrace_path != "")
  lib{cpptrace}: cxx.poptions += "-DCPPTRACE_BACKTRACE_PATH=\"$config.libcpptrace.backtrace_path\""

if ($config.libcpptrace.hard_max_frames != "")
  lib{cpptrace}: cxx.poptions += "-DCPPTRACE_HARD_MAX_FRAMES=$config.libcpptrace.hard_max_frames"

if ($config.libcpptrace.addr2line_path != "")
  lib{cpptrace}: cxx.poptions += "-DCPPTRACE_ADDR2LINE_PATH=\"$config.libcpptrace.addr2line_path\""

if $config.libcpptrace.addr2line_search_system_path
  lib{cpptrace}: cxx.poptions += -DCPPTRACE_ADDR2LINE_SEARCH_SYSTEM_PATH

if (!$config.libcpptrace.std_format)
  lib{cpptrace}: cxx.poptions += -DCPPTRACE_NO_STD_FORMAT

if $config.libcpptrace.unprefixed_try_catch
  lib{cpptrace}: cxx.poptions += -DCPPTRACE_UNPREFIXED_TRY_CATCH

# Compiler-specific options.
#
switch $cxx.id
{
  case 'gcc'
  {
    lib{cpptrace}: cxx.poptions += -DHAS_ATTRIBUTE_PACKED
  }
  case 'clang'
  {
    lib{cpptrace}: cxx.poptions += -DHAS_ATTRIBUTE_PACKED
  }
}

# Import libs.
#
lib{cpptrace}: $impl_libs $intf_libs

# Export options.
#
lib{cpptrace}:
{
  cxx.export.poptions = "-I$out_pfx_inc" "-I$src_pfx_inc"
  cxx.export.libs += $intf_libs
}

# For pre-releases use the complete version to make sure they cannot
# be used in place of another pre-release or the final version. See
# the version module for details on the version.* variable values.
#
if $version.pre_release
  lib{cpptrace}: bin.lib.version = "-$version.project_id"
else
  lib{cpptrace}: bin.lib.version = "-$version.major.$version.minor"

# Don't install private headers.
#
{h hxx}{*}: install = false
